version: '3.5'
services:
  jupyter:
    image: ${REGISTRY}/${USERNAME}/${IMAGENAME}:${IMAGETAG}
    command: start.sh jupyter lab
    volumes:
      - ${PROJECTDIR}:/home/jovyan/demo
    ports: ["8888:8888"]
    networks:
     - datalabframework

networks:
  datalabframework:
    name: datalabframework
    driver: bridge
    external: true
