version: '3.5'
services:
  jupyter:
    image: ${REGISTRY}/${USER}/${IMAGE}:${TAG}
    command: start.sh jupyter lab
    volumes:
      - ${PROJECT_DIR}:/home/jovyan/demo
    ports: ["8888:8888"]
    networks:
     - datalabframework

networks:
  datalabframework:
    name: datalabframework
    driver: bridge
    external: true
